before:
  hooks:
    - go mod download
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - windows
  - darwin
  - linux
archives:
- format_overrides:
    - goos: windows
      format: zip
brew:
  github:
    owner: syntaqx
    name: homebrew-tap
  folder: Formula
  homepage: https://github.com/syntaqx/swarm-api
  description: swarm-api is a simple HTTP server to communicate with Docker Swarm
  test: |
    system "#{bin}/swarm-api --version"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
