version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go mod download
      - run: go test -v ./...
  lint:
    docker:
      - image: golangci/golangci-lint
    steps:
      - checkout
      - run:
          name: run
          command: golangci-lint run || true
  release:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: sudo apt install -y snapd
      - run: sudo snap install snapcraft --classic
      - run: |
          echo $SNAPCRAFT_LOGIN_FILE | base64 --decode --ignore-garbage > snap.login
          snapcraft login --with snap.login
      - run: curl -sL https://git.io/goreleaser | bash
workflows:
  version: 2
  on_commit:
    jobs:
      - lint
      - test
  release:
    jobs:
      - release:
          context: goreleaser
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
