version: 2
jobs:

  test:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go mod download
      - run: go test -v ./...

  lint:
    docker:
      - image: golangci/golangci-lint
    steps:
      - checkout
      - run:
          name: run
          command: golangci-lint run || true

  release:
    docker:
      - image: cibuilds/snapcraft
    steps:
      - checkout
      - run:
          name: install go
          command: |
            export goversion="go1.12.5"
            cd /tmp && wget https://dl.google.com/go/$goversion.linux-amd64.tar.gz
            tar -xvf $goversion.linux-amd64.tar.gz > /dev/null && sudo mv go /usr/local && rm $goversion.linux-amd64.tar.gz
      - run:
          name: validate golang install
          command: |
            export TEMP_PATH="/usr/local/go/bin:$PATH"
            export PATH=$TEMP_PATH
            go version
      - run:
          name: setup snap credentials
          command: |
            mkdir .snapcraft
            echo $SNAPCRAFT_LOGIN_FILE | base64 --decode --ignore-garbage > .snapcraft/snapcraft.cfg
      - run:
          name: run goreleaser
          command: curl -sL https://git.io/goreleaser | bash
workflows:
  version: 2
  on_commit:
    jobs:
      - lint
      - test
  release:
    jobs:
      - release:
          context: goreleaser
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
